### ISSUE TITLE
 腾讯SDK2.9.3崩溃

### ISSUE THREAD

**Issue by wutoz** [candyan/TencentOpenApiSDK#2]
SDK2.9.3中使用了ContainsString: 这个仅支持iOS8以上啊。。很坑。。

**Comment by candyan** [comment]
@wutongr  额~~ 腾讯的SDK我也木有办法。。。先用 2.9.2吧。。下个版本我把 platform 改到 iOS 8.0 。。。让支持 7.0 的不会错用了~~

**Comment by aelam** [comment]
@candyan 不在腾讯吗?

**Comment by candyan** [comment]
@aelam 并不在 我也希望 腾讯可以提供 cocoapods 支持 >_<

**Comment by aelam** [comment]
@candyan can #3 知道为啥子吗
